title: Title
subtitle: Subtitle
author: Author

# Include http://, domain name, but *NO trailing slash*
urlbase: http://example.com

mp3:
  # NOT YET IMPLEMENTED! Do you want to have ID3v2 tags for artist/title automatically set? N.B., may be truncated.
  setartist: true
  settitle:  true

itunes:
  summary: iTunes Summary
  owner: 
    name: Owner
    email: owner@example.com
  # Category MUST be one of the ones listed here http://www.apple.com/itunes/podcasts/specs.html#categories
  category: Comedy
  
s3:
  # Set the relevant s3 endpoint here. For eu-west-1 (Ireland), use this default.
  hostname: s3-eu-west-1.amazonaws.com
  accesskey:
    id: your-aws-access-key-id
    secret: your-aws-access-key-secret
  bucket: example.com
